name: Build Linux kernel for rpi3

on: 
  push:
    branches:
      - main
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential 
    
    - name: Build
      run: |
        git clone https://github.com/buildroot/buildroot.git
        mkdir build
        mkdir buildroot_dl
        cd build
        make BR2_EXTERNAL=../tiny_raspi_buildroot/ O=$PWD -C ../buildroot/ tiny_raspberrypi3_64_defconfig
        make

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build/images
